# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05d243983b97e4fd16e1d4a8aa71e6b1a2e701d577631b4c30f857a54565b4596877db72514ed8ef53920f3bbd1ff64bdda99e28beee2492b518ca1222a6de3a
  api_key: "IIj6UM/2a26I4PpCny4lIO5TjRoe3IU/WQlHGHa9Ga+rGiHOloT0tZPH5FEQQvBNG/C1A9Cw27kK0basWq6X7w=="

test:
  secret_key_base: d5cf2da08e1615a464636d9feb76217064a4426aa58fe8d8b49974061d7de60669e9b13b60efaca24b3e27de145a4055b198cf35109cb773893a67d0159d2652
  api_key: "IIj6UM/2a26I4PpCny4lIO5TjRoe3IU/WQlHGHa9Ga+rGiHOloT0tZPH5FEQQvBNG/C1A9Cw27kK0basWq6X7w=="

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_key: <%= ENV["API_KEY"]%>
